---
all:
  children:
    ios:
      children:
        catalyst_9300:
          hosts:
            c9300-sw01.local:
    nxos:
      children:
        nexus_9000:
          hosts:
            nx9k-sw01.local:
